### PR TITLE
Bump bitlbee-facebook to receive bugfixes

### PR DESCRIPTION
**Pull request by raidancampbell**
See discussion here: https://github.com/bitlbee/bitlbee-facebook/issues/200

### CODE REVIEW

**Comment by mbologna** [comment]
The cleanup part is missing the fix: https://github.com/mbologna/docker-bitlbee/pull/9/files#diff-4d2a8eefdf2a9783512a35da4dc7676a66404b6f3826a8af9aad038722da6823R128

Can you please take care of updating it?

**Comment by raidancampbell** [comment]
D'oh! absolutely.

**Comment by raidancampbell** [comment]
Alrighty, it'll be a bit.  I ran `build.sh` on my mac development laptop to test, and left it in the background to churn.  Turns out it ran through the filesystem and `rm -rf`'d a rather large chunk by the time I got to it.

**Comment by raidancampbell** [comment]
I didn't have a `BITLBEE_VERSION` env variable set, so the script ultimately cd'd me to `~`, tried and failed a bunch of stuff, then tried to cleanup. https://github.com/mbologna/docker-bitlbee/blob/master/build.sh#L9

This sucks, I'll try and get you the fix eventually, but it's fairly low on my priorities now.

**Comment by raidancampbell** [comment]
resolved via `235a1b4d6cc73434738524cda1440826deec4aed`

**Comment by mbologna** [comment]
> I didn't have a `BITLBEE_VERSION` env variable set, so the script ultimately cd'd me to `~`, tried and failed a bunch of stuff, then tried to cleanup. [https://github.com/mbologna/docker-bitlbee/blob/master/build.sh#L9](https://github.com/mbologna/docker-bitlbee/blob/master/build.sh?rgh-link-date=2020-10-20T21%3A51%3A38Z#L9)
> 
> This sucks, I'll try and get you the fix eventually, but it's fairly low on my priorities now.

That's bad, sorry. Weren't you running the docker build in a container?!

**Comment by mbologna** [comment]
> resolved via `235a1b4d6cc73434738524cda1440826deec4aed`

Confirmed. Thanks for taking care of this bump!

**Comment by raidancampbell** [comment]
> > I didn't have a `BITLBEE_VERSION` env variable set, so the script ultimately cd'd me to `~`, tried and failed a bunch of stuff, then tried to cleanup. [https://github.com/mbologna/docker-bitlbee/blob/master/build.sh#L9](https://github.com/mbologna/docker-bitlbee/blob/master/build.sh?rgh-link-date=2020-10-20T21%3A51%3A38Z#L9)
> > This sucks, I'll try and get you the fix eventually, but it's fairly low on my priorities now.
> 
> That's bad, sorry. Weren't you running the docker build in a container?!

I thought I'd be 100% sure the build worked correctly, so I ran `build.sh` without reading it.  I didn't know at the time that it was meant to be executed within docker.

Lessons learned, etc...

**Pull request merged**
